apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git@bitbucket.org:sng-code/kube-base-config.git//base?ref=0.1.5
  - git@bitbucket.org:sng-code/kube-base-app.git//base?ref=0.4.4

  - resources/secret-env-shared.externalsecret.yaml

configMapGenerator:
  - behavior: merge
    envs:
      - .configs/.properties.def.conf
    name: config-env

patches:
  - path: patches/secret-env.externalsecret.yaml
  - target:
      kind: Deployment
      name: app
    path: patches/app.deployment-add-secret-env-shared.yaml
